server:
  port: 80
dubbo:
  application:
    name: web-manager
  registry:
    address: zookeeper://192.168.88.188:2181
  protocol:
    port: -1
  consumer:
    check: false
spring:
  thymeleaf:
    cache: false
