dubbo:
  registry:
    address: zookeeper://192.168.99.222:2181
  protocol:
    port: -1
  application:
    name: web-classes
  consumer:
    check: false
spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  config-location: classpath:mybatis-config.xml
